import {make} from './base.js';
export function attachDialogs(api){function open(o={}){const kind=o.theme||'confirm',gravity=o.gravity||'center',cancellable=o.cancellable!==false,back=make('div','royall-dialog-backdrop gravity-'+gravity),box=make('div','royall-dialog theme-'+kind),head=make('div','royall-dialog-head');head.append(make('div','royall-dialog-icon',o.icon||({confirm:'?',warning:'⚠️',error:'✖️',info:'ℹ️'}[kind]||'⚠️')),make('h3','',o.title||'Dialog'));box.appendChild(head);if(o.text)box.appendChild(make('p','',o.text));const actions=make('div','royall-dialog-actions');box.appendChild(actions);back.appendChild(box);document.body.appendChild(back);function close(){if(!back.parentNode)return;back.classList.remove('show');document.removeEventListener('keydown',key);setTimeout(()=>back.remove(),180)}function key(e){if(cancellable&&e.key==='Escape')close()}if(cancellable){back.onclick=e=>{if(e.target===back)close()};document.addEventListener('keydown',key)}else back.onclick=()=>{};requestAnimationFrame(()=>back.classList.add('show'));return{back,box,actions,close,cancellable}};
api.dialog=open;
api.confirm=function(o={},fn){const d=open({...o,theme:'confirm'}),yes=make('button','royall-dialog-btn confirm',o.confirmText||'Confirm');yes.onclick=()=>{d.close();fn?.()};if(o.showCancel!==false){const no=make('button','royall-dialog-btn cancel',o.cancelText||'Cancel');no.onclick=d.close;d.actions.append(no)}d.actions.append(yes);return d};
api.warning=function(o={},fn){const d=open({...o,theme:'warning'}),yes=make('button','royall-dialog-btn warning',o.confirmText||'Continue');yes.onclick=()=>{d.close();fn?.()};if(o.showCancel!==false){const no=make('button','royall-dialog-btn cancel',o.cancelText||'Cancel');no.onclick=d.close;d.actions.append(no)}d.actions.append(yes);return d};
api.errorDialog=function(o={},fn){const d=open({...o,theme:'error'}),ok=make('button','royall-dialog-btn danger',o.buttonText||'OK');ok.onclick=()=>{d.close();fn?.()};d.actions.append(ok);return d};
api.infoDialog=function(o={},fn){const d=open({...o,theme:'info'}),ok=make('button','royall-dialog-btn info',o.buttonText||'OK');ok.onclick=()=>{d.close();fn?.()};d.actions.append(ok);return d};
api.choice=function(o={},items=[]){const d=open({...o,theme:o.theme||'info'});items.forEach(x=>{const cls=x.theme==='warning'?'warning':x.theme==='danger'?'danger':'info',b=make('button','royall-dialog-btn '+cls,x.text||x[0]||'Option');b.onclick=()=>{d.close();(x.onClick||x[1])?.()};d.actions.append(b)});return d};
api.prompt=function(o={},fn){const d=open({...o,theme:o.theme||'info',gravity:o.gravity||'top'}),input=make('input','royall-dialog-input');input.placeholder=o.placeholder||'';if(o.value!=null)input.value=o.value;d.box.insertBefore(input,d.actions);if(o.showCancel!==false){const no=make('button','royall-dialog-btn cancel',o.cancelText||'Cancel');no.onclick=d.close;d.actions.append(no)}const ok=make('button','royall-dialog-btn info',o.submitText||'OK');ok.onclick=()=>{const v=input.value;d.close();fn?.(v)};d.actions.append(ok);setTimeout(()=>input.focus(),40);return d};
api.clearConfirm=function(target,label='content'){return api.confirm({icon:'🗑️',title:'Clear '+label+'?',text:'This action will clear the current content.',cancelText:'Cancel',confirmText:'Clear'},()=>{if(typeof target==='function')target();else if(target&&'value'in target)target.value=''})}}
